config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      get :complete
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  
  paginates_per 25
  
  validates :title, presence: true
  
  
  
  def status
    if completed == true
      "completed"
    else
      "todo"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action -> { flash.now[:notice] = flash[:notice].html_safe if flash[:html_safe] && flash[:notice] }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update complete destroy ]

  # GET /tasks or /tasks.json
  def index
    @completed = Task.where(completed: true).count
    @todo      = Task.where(completed: false).count
    
    @tasks = Task.order(created_at: :desc)
    if params[:status] == "completed"
      @tasks = @tasks.where(completed: true)
    elsif params[:status] == "all"
      @tasks
    else
      @tasks = @tasks.where(completed: false)
    end
    @tasks = @tasks.page params[:page]
    
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice:  "Task <strong>#{@task.title.titleize}</strong> was created", flash: { html_safe: true } }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def complete
    @task.update(completed: "true")
    redirect_to root_path, notice: "Task <strong>#{@task.title.titleize}</strong> was marked as completed", flash: { html_safe: true }
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_path, status: :see_other, notice: "Task <strong>#{@task.title.titleize}</strong> was deleted", flash: { html_safe: true }}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :title, :description, :completed ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar" data-bs-theme="dark">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">InifiniTask</span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Infinitask" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" >
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4><i class="fa-solid fa-triangle-exclamation"></i> <%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h4>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-6">
      <div class="form-floating mb-3">
        <%= form.text_field :title, class: "form-control", placeholder: "Task Title" %>
        <label for="floatingTitleInput">Task Title</label>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-10">
      <div class="form-floating mb-3">
        <%= form.text_area :description, class: "form-control", placeholder: "Task Description", cols: 30, rows: 10 %>
        <label for="floatingTitleInput">Task Description</label>
      </div>
    </div>
  </div>


  <div class="form-check">
    <%= form.checkbox :completed, class: "form-check-input" %>
    <%= form.label :completed, class: "form-check-label" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <div class="card mb-3 status_<%= task.status %>">
    <div class="card-body">
      <h4><%= task.title.titleize %></h4>
      <blockquote class="blockquote mb-0">
        <p><%= task.description %></p>
      </blockquote>
    </div>
    <div class="card-footer text-body-secondary">
      <div class="btn-group btn-group-sm right">
        <% if task.status == "todo" %>
          <%= link_to ('<i class="fa-solid fa-check"></i>').html_safe, complete_task_path(task), class: "btn btn-light", data: {toggle: "tooltip", placement: "bottom"}, "title"=> "Mark as Done" %>
          <%= link_to ('<i class="fa-solid fa-pencil"></i>').html_safe, edit_task_path(task), class: "btn btn-light", data: {toggle: "tooltip", placement: "bottom"}, "title"=> "Edit Task" %>
        <% end %>
        <%= button_to ('<i class="fa-solid fa-trash-can"></i>').html_safe, task, method: :delete, class: "btn btn-light btn-sm", data: {turbolinks: false, confirm: "Are you sure?", toggle: "tooltip", placement: "bottom"}, "title"=> "Delete Task" %>
      </div>
      <% if task.status == "todo" %>
        Created <%= time_ago_in_words task.created_at %> ago
      <% else %>
        Completed <%= time_ago_in_words task.updated_at %> ago
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"></p>

<% content_for :title, "Tasks" %>


<div class="btn-group btn-group-sm right">
  <%= link_to(tasks_path(status: "all")) do %>
    <div class="btn btn-light position-relative filter">
      <i class="fa-solid fa-filter-circle-xmark"></i> All
    </div>
  <% end %>
  <%= link_to(tasks_path) do %>
    <div class="btn btn-light position-relative filter">
      <i class="fa-solid fa-filter"></i> To Do
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <%= @todo %>
      </span>
    </div>
  <% end %>
  <%= link_to(tasks_path(status: "completed")) do %>
    <div class="btn btn-light position-relative filter">
      <i class="fa-solid fa-filter"></i> Completed
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <%= @completed %>
      </span>
    </div>
  <% end %>

</div>
<h1>Tasks</h1>
<div id="tasks" class="row">
  <div class="col-3">
    <%= link_to(new_task_path) do %>
      <div class="btn btn-primary position-relative">
        <i class="fa-solid fa-plus"></i> New Task
      </div>
    <% end %>
  </div>
  <div class="col-6">
    <%= paginate @tasks %>
  </div>
  
  <div class="row">
    <div class="col-12">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
    </div>
  </div>


  <div class="row">
    <% @tasks.each do |task| %>
      <%= render task %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-6 offset-md-3">
    <%= paginate @tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, data: {turbolinks: false, confirm: 'Are you sure?'}, method: :delete %>
</div>